package greedGame;

import java.awt.event.ActionListener;

import javax.swing.JFrame;
import javax.swing.JTextField;
import javax.swing.JLabel;
import javax.swing.JButton;

/**
 * A small class meant to show a setup frame, and provide the entered values
 * back to the calling method. Mostly generated by WindowBuilder in Eclipse.
 */
public class SetupGUI {

	// The components that is access after creation
	private JFrame frmGreedGame;
	private JTextField pointsToWinText;
	private JTextField bustLimitText;
	private JButton btnReturn;

	/**
	 * Create the application.
	 */
	public SetupGUI() {
		initialize();
	}

	/**
	 * Provides access to the underlying <code>Window</code>s
	 * setVisible(boolean) method
	 * 
	 * @param visible
	 *            <code>true</code> to display the window, <code>false</code> to
	 *            hide it
	 * 
	 * @see javax.swing.JFrame#setVisible(boolean)
	 */
	public void setVisible(boolean visible) {
		frmGreedGame.setVisible(visible);
	}

	/**
	 * Initialize the contents of the frame. Creates a frame and lays out the
	 * subcomponents. Generated by WindowBuilder.
	 */
	private void initialize() {
		frmGreedGame = new JFrame();
		frmGreedGame.setTitle("Setup Game");
		frmGreedGame.setBounds(100, 100, 245, 128);
		frmGreedGame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
		frmGreedGame.getContentPane().setLayout(null);

		pointsToWinText = new JTextField();
		pointsToWinText.setText("10000");
		pointsToWinText.setBounds(10, 25, 100, 20);
		frmGreedGame.getContentPane().add(pointsToWinText);
		pointsToWinText.setColumns(10);

		JLabel lblPointsToWin = new JLabel("Points to win");
		lblPointsToWin.setBounds(10, 11, 100, 14);
		frmGreedGame.getContentPane().add(lblPointsToWin);

		JLabel lblBustLimit = new JLabel("Bust limit");
		lblBustLimit.setBounds(120, 11, 99, 14);
		frmGreedGame.getContentPane().add(lblBustLimit);

		bustLimitText = new JTextField();
		bustLimitText.setText("300");
		bustLimitText.setBounds(120, 25, 99, 20);
		frmGreedGame.getContentPane().add(bustLimitText);
		bustLimitText.setColumns(10);

		btnReturn = new JButton("Start Game");
		btnReturn.setBounds(10, 56, 209, 23);
		frmGreedGame.getContentPane().add(btnReturn);
	}

	/**
	 * Adds a listener that is activated when the user is done setting up the
	 * game and wants to start it
	 * 
	 * @param actionListener
	 *            The listener to add to the start button
	 */
	public void addStartGameActionListener(ActionListener actionListener) {
		btnReturn.addActionListener(actionListener);
	}

	/**
	 * Gets the number of points the user has entered as the limit for when the
	 * game is over
	 * 
	 * @return The number of points entered. Not validated.
	 */
	public int getPointsToWin() {
		return Integer.parseInt(pointsToWinText.getText());
	}

	/**
	 * Gets the number of points the user has entered as the limit for when a
	 * player is bust on the first roll
	 * 
	 * @return The number of points entered. Not validated.
	 */
	public int getBustLimit() {
		return Integer.parseInt(bustLimitText.getText());
	}
}
